defaults: &defaults
  google:
    id: <%= ENV['GOOGLE_ANALYTICS_ID'].presence || nil %>

development:
  <<: *defaults

test:
  <<: *defaults

testing:
  <<: *defaults

qa:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
